### ISSUE TITLE
New crumb is not generated on browser refresh

### ISSUE THREAD

**Issue by genediazjr** [hapijs/crumb#92]
I am not sure if this is just on my machine and if this is the intended design. 
I have tested this on chrome and firefox with the same result.

I have used the following code:
```javascript
const Hapi = require('hapi');
const server = new Hapi.Server();

server.connection({ port: 8001 });
server.register(require('crumb'));
server.route({ 
    path: '/', 
    method: 'get',
    handler: (request, reply) => {
        return reply();
    }
});

server.inject({ url: '/', method: 'get' }, (res) => {

    console.log(res.headers['set-cookie'][0].split(';')[0].replace('crumb=', ''));

    server.inject({ url: '/', method: 'get' }, (res) => {

        // new value is generated
        console.log(res.headers['set-cookie'][0].split(';')[0].replace('crumb=', ''));
    });
});

server.start();
```

Using server.inject generates a new value. But accessing it on the browser does not.

First access.
![1](https://cloud.githubusercontent.com/assets/224404/17881551/eefd44f4-6938-11e6-9455-ba50760eec51.png)

Second access. Still the same crumb value
![2](https://cloud.githubusercontent.com/assets/224404/17881555/001ea6ce-6939-11e6-887f-ba0d3c5a866d.png)

**Comment by stongo** [comment]
This is the expected behavior. In the browser the first request sets the crumb in a cookie. On subsequent requests, if the cookie is already set it doesn't set a new crumb again. 
Since you're not passing a cookie in the `server.inject` calls, it generates a new one every time.
If you want a new crumb generated more frequently, set a low cookie expiry using the plugins' `cookieOptions`

**Comment by genediazjr** [comment]
I see. Thank you for clarifying.
